---
- name: Include OS specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
      - "{{ ansible_os_family }}-{{ ansible_distribution_major_version}}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/defaults"
      skip: true
  tags:
    - vars
    - -x-windows-managers

- name: Ensure that a miminal X Windows is installed
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ windows_manager_pkgs }}"
  tags:
  - x-windows-managers

- name: Install epel
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present
  tags:
  - epel
  - x-windows-managers

- name: Ensure that the desired X-Windows Managers are installed from EPEL
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes"
    enablerepo: "epel"
  loop: "{{ windows_manager_pkgs_epel }}"
  tags:
  - epel
  - x-windows-managers

